spring.application.name=employee-management-system-backend

Spring.datasource.url=jdbc:MySQL://localhost:3306/employee_management_system_db
Spring.datasource.username=root
Spring.datasource.password=Root
Spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#JPA Properties:
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

